logging:
  level:
    root: info
    org.codebusters: ${AGENT_LOG_LEVEL:info}

spring:
  datasource:
    # jdbc:postgresql://localhost:5432/dbName
    url: ${AGENT_DATABASE_DATASOURCE_URL}
    username: ${AGENT_DATABASE_USER}
    password: ${AGENT_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: ${AGENT_DATABASE_POOL_SIZE:5}
      connection-timeout: ${AGENT_DATABASE_CONNECTION_TIMEOUT:5000}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
  mvc:
    throw-exception-if-no-handler-found: true

jwt:
  secret: ${AGENT_SECRET}

agent:
  genre:
    max-length: ${AGENT_GENRE_MAX_LENGTH:100}
    char-whitelist: ${AGENT_GENRE_CHAR_WHITELIST:}
