
@startuml

hide circle
skinparam linetype ortho

entity "user" as user {
  *id : uuid
}

entity "genre" as genre {
  *id : uuid <<generated>>
  --
  *name : varchar
}

entity "userGenre" as userGenre {
  *user_id : uuid <<PK,FK1>>
  *genre_id : uuid <<PK,FK2>>
  --
}

user ||..o{ userGenre
userGenre }o..|| genre

@enduml