version: "3.4"
services:
  preferencesagent:
    build:
      dockerfile: .docker/Dockerfile
      context: ../
    container_name: preferencesagent
    environment:
      JVM_OPTS: -Xmx512m -Xms512m
      AGENT_LOG_LEVEL: debug
      AGENT_DB_URL: jdbc:postgresql://agent-postgres:5432/agent?createDatabaseIfNotExist=true
      AGENT_SECRET: eme2dqb1TKMqmdoI2n9ooO91z6Ag9d7raJXwj70crls7Djmb9-hCok3nETJkg1ANP6EHraOkpoRLRzQWusecmg
      AGENT_DB_USER: agent
      AGENT_DB_PASSWORD: agent
    ports:
      - "6500:6500"
    depends_on:
      - agent-postgres

  agent-postgres:
    image: postgres:14.4
    container_name: agent-postgres
    environment:
      POSTGRES_PASSWORD: agent
      POSTGRES_USER: agent

  agent-pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: agent-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: codebusters@ironhills.dev
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "6550:80"

  agent-openapi:
    image: swaggerapi/swagger-ui
    container_name: agent-openapi
    volumes:
      - ../doc/openapi:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi/preferences-agent.yml

  agent-nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    container_name: agent-nginx
    ports:
      - "6580:80"
    depends_on:
      - preferencesagent
      - agent-openapi